artifact_location: /Users/msankhane/Desktop/Orchestration/kedro-road-sign/runs/mlflow/996350201112225426
creation_time: 1748253746334
experiment_id: '996350201112225426'
last_update_time: 1748253746334
lifecycle_stage: active
name: /Shared/Ultralytics
