artifact_location: /Users/msankhane/Desktop/Orchestration/kedro-road-sign/runs/mlflow/0
creation_time: 1748253746316
experiment_id: '0'
last_update_time: 1748253746316
lifecycle_stage: active
name: Default
